vim.opt.runtimepath:prepend(vim.fn.getcwd())
local temp = vim.fn.tempname()
vim.fn.mkdir(temp .. "/src","p")
vim.fn.writefile({'[package]','name = "rustyeyes-test"','version = "0.1.0"','edition = "2021"'},temp .. "/Cargo.toml")
local file = temp .. "/src/main.rs"
vim.fn.writefile({'fn main() { let answer: i32 = "hello"; println!("{answer}"); }'},file)
vim.cmd.edit(vim.fn.fnameescape(file))
require("cargo_diagnostics").setup()
local ns = vim.api.nvim_create_namespace("cargo_diagnostics")
require("cargo_diagnostics").check()
assert(vim.wait(30000,function() return #vim.diagnostic.get(nil,{namespace=ns}) > 0 end,100),"Cargo diagnostic not received")
vim.fn.writefile({'fn main() { let answer: i32 = 42; println!("{answer}"); }'},file)
vim.cmd.edit(vim.fn.fnameescape(file))
require("cargo_diagnostics").check()
assert(vim.wait(30000,function() return #vim.diagnostic.get(nil,{namespace=ns}) == 0 end,100),"Corrected diagnostic not cleared")
print("Cargo integration passed: invalid -> diagnostic -> corrected -> cleared")
vim.cmd("qa!")
